version: '3'
services:
  dbpostgres:
    image: postgres
    volumes:
      - ./questionmicro_db-data:/var/lib/postgresql/data
    ports:
      - "5450:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: questionmicro_db

volumes:
  questionmicro_db-data: